version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.11.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/debian-repository-tools
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/build-files/gnumake && make
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.14.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/debian-repository-tools
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/build-files/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
