version: 2
jobs:
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.15.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/debian-repository-tools
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/library/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/library/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/library/tests/build-files/gnumake && ./CodeSmithyDebianRepositoryToolsTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyDebianRepositoryTools.xml
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/debian-repository-tools/cli/build-files/gnumake && make
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/CodeSmithyDebianRepositoryTools.xml
          destination: CodeSmithyDebianRepositoryTools-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/CodeSmithyDebianRepositoryTools.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
